package main

import (
	"encoding/json"
	"errors"
	"os/exec"
	"strings"
	"testing"
)

// TestCheckConfigEnableProcessExecValid: -check-config accepts process execution
// enabled with a valid (default) grace period, without binding a port or spawning
// anything.
func TestCheckConfigEnableProcessExecValid(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a binary; skipped in -short")
	}
	bin := buildSteward(t)

	cmd := exec.Command(bin, "-check-config", "-enable-process-exec", "-addr", "127.0.0.1:0")
	cmd.Env = stewardEnv()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("-check-config with -enable-process-exec must exit 0, got %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "configuration valid") {
		t.Errorf("-check-config did not print the validation success line:\n%s", out)
	}
}

// TestCheckConfigNonPositiveGraceRejected: with execution enabled, a non-positive
// stop grace period is a fail-closed startup error naming the flag.
func TestCheckConfigNonPositiveGraceRejected(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a binary; skipped in -short")
	}
	bin := buildSteward(t)

	cmd := exec.Command(bin, "-check-config", "-enable-process-exec",
		"-process-stop-grace-period", "0s", "-addr", "127.0.0.1:0")
	cmd.Env = stewardEnv()
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected a non-zero exit for a non-positive grace period, got success:\n%s", out)
	}
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("expected an ExitError, got %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "process-stop-grace-period") {
		t.Errorf("startup error does not name -process-stop-grace-period:\n%s", out)
	}
}

// TestCheckConfigNonPositiveGraceIgnoredWhenExecDisabled: the grace period is only
// validated when execution is enabled; a non-positive value on an exec-disabled
// node must not fail a config that never uses it.
func TestCheckConfigNonPositiveGraceIgnoredWhenExecDisabled(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a binary; skipped in -short")
	}
	bin := buildSteward(t)

	cmd := exec.Command(bin, "-check-config", "-process-stop-grace-period", "0s", "-addr", "127.0.0.1:0")
	cmd.Env = stewardEnv()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("a non-positive grace with exec disabled must be accepted, got %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "configuration valid") {
		t.Errorf("-check-config did not print the validation success line:\n%s", out)
	}
}

// TestEnableProcessExecMalformedEnvExitsNonZero: STEWARD_ENABLE_PROCESS_EXEC gates
// real command execution, so a set-but-unparseable value must fail closed, never
// silently pick the executing (or non-executing) side.
func TestEnableProcessExecMalformedEnvExitsNonZero(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a binary; skipped in -short")
	}
	bin := buildSteward(t)

	cmd := exec.Command(bin, "-check-config", "-addr", "127.0.0.1:0")
	cmd.Env = stewardEnv("STEWARD_ENABLE_PROCESS_EXEC=maybe")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected a non-zero exit for STEWARD_ENABLE_PROCESS_EXEC=maybe, got success:\n%s", out)
	}
	if !strings.Contains(string(out), "STEWARD_ENABLE_PROCESS_EXEC") {
		t.Errorf("startup error does not name the env var:\n%s", out)
	}
}

// TestProcessStopGraceMalformedEnvExitsNonZero: a set-but-unparseable duration is a
// fail-closed startup error naming the env var and the bad value.
func TestProcessStopGraceMalformedEnvExitsNonZero(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a binary; skipped in -short")
	}
	bin := buildSteward(t)

	cmd := exec.Command(bin, "-check-config", "-addr", "127.0.0.1:0")
	cmd.Env = stewardEnv("STEWARD_PROCESS_STOP_GRACE_PERIOD=10sec")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected a non-zero exit for a malformed grace duration, got success:\n%s", out)
	}
	if !strings.Contains(string(out), "STEWARD_PROCESS_STOP_GRACE_PERIOD") {
		t.Errorf("startup error does not name the env var:\n%s", out)
	}
}

// TestSchemaIncludesProcessExecFields: the -config JSON schema is generated by
// reflecting over fileConfig, so the two new keys appear automatically with the
// right types. This pins that they are present and typed as expected.
func TestSchemaIncludesProcessExecFields(t *testing.T) {
	raw, err := configSchemaJSON()
	if err != nil {
		t.Fatalf("configSchemaJSON: %v", err)
	}
	var schema struct {
		Properties map[string]map[string]any `json:"properties"`
	}
	if err := json.Unmarshal(raw, &schema); err != nil {
		t.Fatalf("decode schema: %v", err)
	}
	if got := schema.Properties["enable_process_exec"]["type"]; got != "boolean" {
		t.Errorf("enable_process_exec type=%v, want boolean", got)
	}
	if got := schema.Properties["process_stop_grace_period"]["type"]; got != "string" {
		t.Errorf("process_stop_grace_period type=%v, want string", got)
	}
}
